- icon: icon-user-md
  title: European Facial
  description: A deep pore-cleansing treatment that includes a thorough cleansing, exfoliating, extractions and a custom prescription mask. The final moisturizing & facial massage leaves skin feeling amazingly healthy. Also includes anti-aging eye and hand treatment.

- icon: icon-diamond
  title: Express Facial
  description: Deep pore cleansing, extractions, mask and hydration. Perfect for teens or people on the go.

- icon: icon-flask
  title: Enzyme Resurfacing Facial
  description: Enzymes remove dead skin cells that make skin appear dull. This noninvasive treatment leaves skin refreshed, smooth, and soft. Fine lines and wrinkles are diminished. Includes anti-aging or skin brightening mask.

- icon: icon-globe
  title: Glycolic Acid Treatment or Salicylic Acid Treatment
  description: Eliminates dead surface cells for radiant skin. Includes hydrating mask.Series of six is recommended for maximum results.

- icon: icon-bed
  title: Microdermabrasion
  description: Tiny crystals gently, yet effectively buff away outer layers of the skin. Acne scarring, fine lines and other skin imperfections benefit dramatically from this treatment.

- icon: icon-bed
  title: Waxing Services
  description: Got hair growing everywhere? Let's pull it! 
